### PR TITLE
Fix invalid dependency type

### PR DESCRIPTION
**Pull request by h0rn3z0r**
`dependency-graph` package should be moved from `devDependencies` to `dependencies` as it is required in a code below:
https://github.com/recursive-beast/laravel-mix-manifest-paths/blob/9f57ecdafd5c125c56177d2830806588c2120de4/src/compilation.ts#L4
Currently this package produces `Cannot find module 'dependency-graph'` error on `yarn mix` after clean installation.

### CODE REVIEW

**Comment by recursive-beast** [comment]
uninstall `dependency-graph` then reinstall it as a dependency so that `package-lock.json` is updated as well

**Comment by h0rn3z0r** [comment]
@recursive-beast, should be ok now.

**Comment by recursive-beast** [comment]
@h0rn3z0r travis-ci stopped the unlimited support for open source projects, I'll try to migrate to github actions today, but until then, your commit will not be released as a new version of the npm package.

**Pull request merged**
